version: '3.8'

services:
  # Single container running both frontend and backend
  messagecraft:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: messagecraft-app
    ports:
      - "80:80"        # Frontend (Nginx)
      - "8000:8000"    # Backend API (FastAPI)
    environment:
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # Database
      - DATABASE_URL=${DATABASE_URL}
      
      # AI Configuration
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      
      # App Configuration
      - ENVIRONMENT=production
      
      # Frontend API URL (internal)
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - messagecraft-network

  # Alternative: Separate containers for each service
  # Uncomment below for production-style deployment

  # backend:
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #   container_name: messagecraft-backend
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - SUPABASE_URL=${SUPABASE_URL}
  #     - SUPABASE_KEY=${SUPABASE_KEY}
  #     - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
  #     - DATABASE_URL=${DATABASE_URL}
  #     - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
  #     - ENVIRONMENT=production
  #   volumes:
  #     - ./backend/logs:/app/logs
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   restart: unless-stopped
  #   networks:
  #     - messagecraft-network

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   container_name: messagecraft-frontend
  #   ports:
  #     - "80:80"
  #   environment:
  #     - VITE_API_URL=http://backend:8000
  #   depends_on:
  #     - backend
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   restart: unless-stopped
  #   networks:
  #     - messagecraft-network

networks:
  messagecraft-network:
    driver: bridge